### ISSUE TITLE
bootstrap table no wrap

### ISSUE THREAD

**Issue by billzt** [billzt/btcotton#27]
According to https://github.com/wenzhixin/bootstrap-table/issues/2476 , Using 
```css
<style>
    td {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
</style>
```

can render long bootstrap table in a well method without `class="table-responsive"`

Now this is only used with sample statistics.
